# Generated by Django 2.2.10 on 2020-02-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('student_class', models.CharField(max_length=100)),
                ('student_section', models.CharField(max_length=5)),
                ('telgu_mark', models.IntegerField()),
                ('hindi_mark', models.IntegerField()),
                ('english_mark', models.IntegerField()),
                ('math_mark', models.IntegerField()),
                ('science_mark', models.IntegerField()),
                ('social_mark', models.IntegerField()),
            ],
        ),
    ]
